### ISSUE TITLE
Behavior of the letter 'j'

### ISSUE THREAD

**Issue by jorjun** [antoineboquet/greek-conversion#1]
Hi.. love the library and have only just begun exploring.. but I have a question why does an English word containing 'J' stay as 'J' when converted to Greek letters? Is there a setting to stop this?

**Comment by antoineboquet** [comment]
Hi, this is because the character 'j' doesn't have counterpart in greek depending on the available mapping. I can imagine an option to remove the characters that aren't mapped:
```diff
export interface ConversionOptions {
  preserveWhitespace?: boolean,
  removeDiacritics?: boolean,
+ removeNonGreekCharacters?: boolean
}
```
Do you agree with this?

**Comment by jorjun** [comment]
No, in the specific case of J isn't there a combination of greek letters that could be substituted?

**Comment by antoineboquet** [comment]
No, letter J remains unemployed by typical transliteration systems. Sometimes it's used in 'beta code' to represent word-final sigmas but it's a little bit weird in my opinion. Also there are fewer letters in greek than in latin and I think it's interesting to note that letter J is of modern usage and didn't exist yet in classical latin (I & J were equivalent).

**Comment by jorjun** [comment]
Ἰησοῦς sums to 888 using gematria and it has seemed reasonable for at least a century to use those two greek characters for the initial J.

**Comment by antoineboquet** [comment]
Do you think that any 'ιη' should be converted in J and vice versa? If so can you give me some examples from scholar or other 'authoritative' sources, please? Because I'm not used to this transliteration.

**Comment by jorjun** [comment]
If you google for 'Ιησους' you will find fair number of results.

This site might one of the more reputable: https://biblehub.com/greek/2424.htm

**Comment by antoineboquet** [comment]
Sorry but I don't understand as your link shows this:
![image](https://github.com/antoineboquet/greek-conversion/assets/4170700/8441c550-4303-4b40-92be-6c092b1abe9c)

**Comment by jorjun** [comment]
You believe it best to leave J which is a non-greek letter in the Greek transliteration rather than convert them to Ἰη? That's the summary?

**Comment by antoineboquet** [comment]
I believe this is not what most users expect and you didn't give me an evidence of this usage. Another solution would be to make the J a dead key, but I'm not sure this is a good one too. I'm open to discuss this further and it would be interesting if other people joined the discussion, but for now I'm not convinced I need to change current behavior.

**Comment by jorjun** [comment]
The other library I am looking at is: greek-utils
Which transliterates j to ξ also not ideal, but at least all of the letters are greek.

joseph -> ξοσεπη

**Comment by antoineboquet** [comment]
But as you know it makes a duplicate as ξ is already represented by 'c' in beta code and 'x' in romanized form. Which is not very satisfactory... and not standard in the end.
